import type { IntelligenceLevel, IntelligenceProfile } from './types';

export const intelligenceProfiles: Record<IntelligenceLevel, IntelligenceProfile> = {
  instant: { level: 'instant', name: 'Instant Flash', description: 'Jawaban tercepat, singkat, langsung inti.', bestFor: ['sapaan', 'definisi cepat', 'caption pendek', 'riset awal'], retrievalTopK: 2, temperature: 0.22, maxOutputTokens: 500, reasoningDepth: 'low', verificationPasses: 0 },
  ordinary: { level: 'ordinary', name: 'Ordinary Flash', description: 'Jawaban ringan untuk obrolan harian.', bestFor: ['obrolan harian', 'ringkasan pendek', 'command umum'], retrievalTopK: 3, temperature: 0.25, maxOutputTokens: 750, reasoningDepth: 'standard', verificationPasses: 0 },
  medium: { level: 'medium', name: 'Medium Flash', description: 'Masih ringan, sedikit lebih jelas.', bestFor: ['tugas pendek', 'debug ringan', 'penjelasan singkat'], retrievalTopK: 4, temperature: 0.28, maxOutputTokens: 1000, reasoningDepth: 'medium', verificationPasses: 1 },
  high: { level: 'high', name: 'High Flash', description: 'Batas atas Flash untuk kasus agak teknis.', bestFor: ['ringkasan teknis', 'bug sederhana', 'cek cepat'], retrievalTopK: 5, temperature: 0.25, maxOutputTokens: 1400, reasoningDepth: 'high', verificationPasses: 1 },
  thinking: { level: 'thinking', name: 'Thinking Flash', description: 'Mode terdalam Flash, tetap tidak seberat Lite/Max.', bestFor: ['analisis pendek multi-step', 'validasi cepat'], retrievalTopK: 6, temperature: 0.24, maxOutputTokens: 2000, reasoningDepth: 'deep', verificationPasses: 1 },
};

export function normalizeIntelligenceLevel(input?: string | null): IntelligenceLevel { const text = String(input || '').toLowerCase().trim(); if (text === 'instant' || text === 'flash') return 'instant'; if (text === 'ordinary') return 'ordinary'; if (text === 'medium' || text === 'lite') return 'medium'; if (text === 'high') return 'high'; if (text === 'thinking' || text === 'thingking' || text === 'deep' || text === 'max') return 'thinking'; return 'instant'; }
export function getIntelligenceProfile(input?: string | null): IntelligenceProfile { return intelligenceProfiles[normalizeIntelligenceLevel(input)]; }
export function buildLevelInstruction(profile: IntelligenceProfile): string { const base = `Level aktif: ${profile.name}. Kedalaman: ${profile.reasoningDepth}. Retrieval topK: ${profile.retrievalTopK}. Verifikasi: ${profile.verificationPasses} pass.`; if (profile.level === 'instant') return `${base} Jawab pendek, cepat, langsung inti. Jika topik berat, sarankan Lite/Max.`; if (profile.level === 'ordinary') return `${base} Jawab natural dan ringan, jangan melebar.`; if (profile.level === 'medium') return `${base} Beri langkah ringkas dan validasi singkat.`; if (profile.level === 'high') return `${base} Analisis cukup teliti tapi tetap hemat token.`; return `${base} Beri struktur tujuan, asumsi, solusi, validasi singkat. Jangan mengarang.`; }
